apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: pull-autoscaler-demo
spec:
  scaleDownDelaySecondsAfterScaleOut: 30
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: azure-runners
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    # A repository name is the REPO part of `github.com/OWNER/REPO`
    - https://github.com/bosch-ecs-career-camp/final-project