apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: azure-runners
  namespace: default 
  labels:
    - demo
    - azure
spec:  
  template:
    spec:
      repository: bosch-ecs-career-camp/final-project
      image: stream4acr.azurecr.io/final-project:f3c34f.v88
      