apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: azure-runners
  namespace: default 
spec:
  replicas: 0
  template:
    spec:
      repository: bosch-ecs-career-camp/final-project
      image: stream4acr.azurecr.io/final-project:1112da.v51
      labels: 
        - azure
        - aks
      env:
      - name: RUNNER_FEATURE_FLAG_EPHEMERAL
        value: true
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runners-autoscaler
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    kind: RunnerDeployment
    # # In case the scale target is RunnerSet:
    # kind: RunnerSet
    name: azure-runners
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      duration: "5m"