# apiVersion: actions.summerwind.dev/v1alpha1
# kind: RunnerDeployment
# metadata:
#   name: example-runnerdeploy
# spec:
#   replicas: 1
#   template:
#     spec:
#       repository: bosch-ecs-career-camp/final-project
#       image: stream4acr.azurecr.io/final-project:445f55.v32


# apiVersion: actions.summerwind.dev/v1alpha1
# kind: RunnerSet
# metadata:
#   name: runner-deploy
# spec:
#   replicas: 1
#   repository: bosch-ecs-career-camp/final-project
#   image: stream4acr.azurecr.io/final-project:445f55.v32
#   selector:
#     matchLabels:
#       app: runner-deploy
#   serviceName: runner-deploy
#   template:
#     metadata:
#       labels:
#         app: runner-deploy

apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: runner-deployment
spec:
  template:
    spec:
      repository: bosch-ecs-career-camp/final-project
      image: stream4acr.azurecr.io/final-project:4e1276.v46
      
---
# apiVersion: actions.summerwind.dev/v1alpha1
# kind: HorizontalRunnerAutoscaler
# metadata:
#   name: runner-deployment-autoscaler
# spec:
#   # Runners in the targeted RunnerDeployment won't be scaled down
#   # for 5 minutes instead of the default 10 minutes now
#   scaleDownDelaySecondsAfterScaleOut: 300
#   scaleTargetRef:
#     kind: RunnerDeployment
#     # # In case the scale target is RunnerSet:
#     # kind: RunnerSet
#     name: runner-deployment
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#   - type: PercentageRunnersBusy
#     scaleUpThreshold: '0.75'
#     scaleDownThreshold: '0.25'
#     scaleUpFactor: '2'
#     scaleDownFactor: '0.5'
