name: Docker job Demo
on:
  
  workflow_dispatch:

jobs:  
  container:    
    runs-on: ['azure', 'demo']
    container:
      image: node:14.15.0-alpine3.12

    steps:
      - name: Run inside container
        run: |
          node -v
          cat /etc/os-release 
      
      - name: Use another container
        uses: docker://node:12.14.1
        with:
          entrypoint: /bin/cat
          args: /etc/os-release