name: Building Versioning and Pushing the Image

on:
  workflow_dispatch:

env:
  #RUNNER_VERSION: "2.303.0"
  ACR_NAME: stream4acr
  
jobs:
  build-push-and-versioning:
    runs-on: ubuntu-latest
    steps:      
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      # - name: "Login via Azure CLI"
      #   uses: azure/login@v1.4.5
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - name: "Create Azure Container Registry"  
      #   run: |
      #    acrLength=`az acr list --query "[?name=='${{ env.ACR_NAME }}']"`
      #    [[ ${#acrLength} -gt 3 ]] && echo "acr ${{ env.ACR_NAME }} exist" || \
      #    az acr create --resource-group ${{ env.R_GROUP }} \
      #    --name ${{ env.ACR_NAME }} --sku Basic \
      #    --admin-enabled true 
         

      # - name: Azure CLI script file
      #   uses: azure/CLI@v1
      #   with:
      #     azcliversion: 2.46.0
      #     inlineScript: |
      #       chmod +x $GITHUB_WORKSPACE/scripts/acr_create.sh
      #       $GITHUB_WORKSPACE/scripts/acr_create.sh

      - name: "Azure Container Registry Login"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ env.ACR_NAME }}
          password: ${{ secrets.REG_PASS }}
      - name: "Build and Push Runner image"
        run: |
          count=$(git rev-list --all --count)
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/final-project:${GITHUB_SHA::6}.v$count .      
          docker push ${{ env.ACR_NAME }}.azurecr.io/final-project:${GITHUB_SHA::6}.v$count


      