name: Building Versioning and Pushing the Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'build/Dockerfile'

env:
  # image container registry name
  ACR_NAME: stream4acr
  
jobs:
  build-push-and-versioning:
    runs-on: ubuntu-latest
    steps:      
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0   

      # - name: "Azure Container Registry Login"
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: ${{ env.ACR_NAME }}.azurecr.io
      #     username: ${{ env.ACR_NAME }}
      #     password: ${{ secrets.REG_PASS }}
      - name: "Build and Push Runner image"
        id: tag
        run: |
          count=$(git rev-list --all --count)
          export TAG=${GITHUB_SHA::6}.v$count        
          echo $TAG >> $GITHUB_ENV
          echo $TAG > tag
  #        docker build -t ${{ env.ACR_NAME }}.azurecr.io/final-project:$TAG build/      
  #        docker push ${{ env.ACR_NAME }}.azurecr.io/final-project:$TAG

      - name: Save TAG 
        uses: actions/upload-artifact@v3
        with:
          name: tagging
          path: tag

      - name: Generate list using Markdown
        run: |
          echo "### Successfully complete the job with the following details :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Successfully build image final-project:${{ steps.tag.outputs.TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "- Successfully push to ACR ${{ env.ACR_NAME }}.azurecr.io" >> $GITHUB_STEP_SUMMARY
          echo "- Access URL is ${{ env.ACR_NAME }}.azurecr.io/final-project:${{ steps.tag.outputs.TAG }}" >> $GITHUB_STEP_SUMMARY
                    
      