name: Create Infrastructure and Deploy Runner Controller

on:
  workflow_dispatch: 

jobs:
  build-aks-deploy-runner:
    runs-on: ubuntu-latest
    steps:      
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3.0.2
       
      - name: Azure Login
        uses: azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}          

      - name: Create AKS and attach ARC
        uses: azure/CLI@v1
        with:
          azcliversion: 2.46.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/src/infra_build.sh
            $GITHUB_WORKSPACE/src/infra_build.sh

      - name: Install KubeControl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.3'
        id: install

      - name: Download TAG
        uses: dawidd6/action-download-artifact@v2
        with: 
          workflow: image_build.yml     
              
      - name: Deploy Runners
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          export TAG=`cat tagging/tag`
          src/deploy_runners.sh
        shell: bash


      

      