name: Local runner test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu
      #['azure', 'demo']
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
         
      
  job2:
    runs-on: ['azure', 'demo']
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

  job3:
    runs-on: ['azure', 'demo']
    steps:    
      - name: "Login via Azure CLI"
        uses: azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
  job4:
    runs-on: ['azure', 'demo']
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
  
  job5:
    runs-on: ['azure', 'demo']
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2