name: Local runner test

on:
  workflow_dispatch:

jobs:
 
  job3:
    runs-on: ubuntu-latest
    steps:    
      - name: "Login via Azure CLI"
        uses: azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 