name: Local runner test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Display Terraform Version
        run: terraform --version      
      
  job2:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

  job3:
    runs-on: self-hosted
    steps:    
      - name: "Login via Azure CLI"
        uses: azure/login@v1.4.5
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}